# FROM nvidia/cuda:12.8.0-cudnn-runtime-ubuntu22.04
FROM nvidia/cuda:13.1.2-cudnn-runtime-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# =========================
# System dependencies
# =========================
RUN apt-get update && apt-get install -y \
    build-essential \
    libsndfile1 \
    libgomp1 \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    git \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# =========================
# Python venv (root luôn)
# =========================
RUN python3 -m venv /venv

ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:/usr/local/cuda/bin:$PATH"

ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"

# =========================
# Copy source
# =========================
COPY . /app

# =========================
# Install Python deps
# =========================
RUN pip install --upgrade pip && \
    pip install \
    torchcodec==0.11 \
    torch==2.8.0+cu128 \
    torchaudio==2.8.0+cu128 \
    --index-url https://download.pytorch.org/whl/cu128

# Install local project
RUN pip install -e .

# =========================
# Runtime config
# =========================
ENV OMNIVOICE_LOG_LEVEL=info
ENV HF_HOME=/tmp/huggingface

EXPOSE 8880

CMD ["omnivoice-server", "--host", "0.0.0.0", "--port", "8880", "--profile-dir", "/app/profiles", "--device", "cuda"]
